version: "3.7"
services:
  client:
    container_name: gulpin_client
    build:
      dockerfile: ./Dockerfile
      context: ./client
    ports:
      - "3000:3000"
  server:
    container_name: gulpin_server
    build:
      dockerfile: ./Dockerfile
      context: ./server
    ports:
      - "8080:8080"
      - "5432:5432"
    environment:
      DATABASE_URL: "postgres://gulpin:dev@localhost:5432/game-db"
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # volumes:
    #   - cache:/data
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gulpin
      POSTGRES_DB: game-db
      POSTGRES_PASSWORD: dev
